Repository YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO, pull requests merged in 2022-12, with the labels that each got.

#85 Update pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement, good first issue

#87 Update the preview link in the Pull Request Template
  .github/pull_request_template.md
Labels: enhancement

#89 Remove unwanted comments in the Pull Request Template
  .github/pull_request_template.md
Labels: enhancement

#91 Add new comments to the Pull Request Template
  .github/pull_request_template.md
Labels: documentation, enhancement
